### ISSUE TITLE
Buttons next and last image with multi image not align using vue 3 ts

### ISSUE THREAD

**Issue by skatesham** [XiongAmao/vue-easy-lightbox#119] opened 2022-12-06 19:43 UTC
Why?
Install `Vue3` and `vue-easy-lightbox@next`  
And using "hello world" using type option and composition api  
The buttons are not align as live demo.
![Screenshot from 2022-12-06 16-39-26](https://user-images.githubusercontent.com/17432957/206007333-9be3470e-00da-482e-ad5c-60ad52c96331.png)

As the above image show, the next and last button are on the up side of the view.

`npm init vue@latest` // "vue": "^3.2.45",
 +  
Code: https://onycat.com/vue-easy-lightbox/guide/#basic-usage-in-sfc

**Comment by XiongAmao** [comment] 2022-12-09 10:32
Hi,
I can't reproduce this issue, can you provide a repo?

**Comment by Ramon1987** [comment] 2022-12-14 09:00
Same problem as Skateham! Button alignment on top of screen :(

**Comment by XiongAmao** [comment] 2022-12-15 07:29
@Ramon1987 
HI, can you provide a simple repo or some code?
I'm not sure what the problem is.

**Comment by rafalfigura** [comment] 2023-01-07 23:14
> Same problem as Skatesham! Button alignment on top of screen :(
> 
> added this:
> 
> :deep(.vel-btns-wrapper) { width : 100%; height : 100%; }
> 
> But now it doesnt close when clicking outside image

Works for me. Thanks!

**Comment by XiongAmao** [comment] 2023-02-03 14:21
@skatesham @Ramon1987 @rafalfigura 
Hi, guys

This issue has been fixed in v1.12.0.

**Closed by XiongAmao** 2023-02-03 14:21 UTC
